introduce MCAP CLI tool during installation just as a reference.
eProsima/DDS-Record-Replay pull request #111
Opened 2024-01-13 17:40 UTC by fujitatomoya

address https://github.com/eProsima/DDS-Record-Replay/issues/109

2024-01-13 17:42 UTC, fujitatomoya commented on docs/rst/developer_manual/installation/sources/linux.rst
> +    To work with MCAP files via command line interface, you can use `MCAP CLI <https://mcap.dev/guides/cli>` _ to manage the data in MCAP files.
i thought we do not want to `MCAP CLI` usage and details in eProsima doc here for the maintenance. instead, we can introduce that there is `MCAP CLI` that we can use to manage the saved MCAP files via command line interface here.

2024-01-13 17:43 UTC, fujitatomoya commented
@juanlofer-eprosima can you take a look when you have time?

2024-01-15 07:35 UTC, rsanchez15 approved these changes

2024-01-16 09:32 UTC, rsanchez15 requested changes
Hi @fujitatomoya, could you rebase this to `main` branch? Then we should be able to merge it.

2024-01-16 23:36 UTC, fujitatomoya commented
@rsanchez15 done rebase against upstream/main.

2024-01-17 06:09 UTC, merged