[20509] Update repository for Fast DDS 3.0.0 compatibility
eProsima/DDS-Record-Replay pull request #148
Opened 2024-06-18 07:15 UTC by LuciaEchevarria99

Merge after:
-  **Fast-DDS:** https://github.com/eProsima/Fast-DDS/pull/4779
- **dev-utils:** https://github.com/eProsima/dev-utils/pull/101
- **DDS-Pipe:** https://github.com/eProsima/DDS-Pipe/pull/111

2024-07-22 09:17 UTC, Tempate requested changes

2024-07-22 09:17 UTC, Tempate commented on ddsreplayer/test/blackbox/mcap/resources/configuration.mcap
Please leave somewhere the command you used to record the MCAP.

2024-07-22 14:01 UTC, Tempate commented on ddsreplayer/test/blackbox/mcap/resources/configuration.mcap
Thinking about it a bit more, I believe we should include a README.md in `resources` that explains how to generate the different files and the configuration files of the DdsRecorder used to generate them.

2024-09-02 10:58 UTC, juanlofer-eprosima requested changes

2024-09-02 10:58 UTC, juanlofer-eprosima commented on ddsrecorder_participants/src/cpp/recorder/mcap/McapHandler.cpp
> +        // TODO Warning
Please do these.

2024-09-02 10:58 UTC, juanlofer-eprosima commented on ddsrecorder_participants/src/cpp/recorder/mcap/McapHandler.cpp
> +    fastdds::rtps::CDRMessage_t* cdr_message = new fastdds::rtps::CDRMessage_t(payload);
NIT: you can remove the wraps thing at the end since this constructor already sets it.

2024-09-02 10:58 UTC, juanlofer-eprosima commented on ddsreplayer/src/cpp/tool/DdsReplayer.cpp
> +    // // Register in factory
```suggestion
    // Register in factory
```

2024-09-02 10:58 UTC, juanlofer-eprosima commented on ddsrecorder_participants/src/cpp/recorder/mcap/McapHandler.cpp
> +            logError(DDSRECORDER_MCAP_HANDLER, "MCAP_WRITE | Failed to serialize DynamicType to idl for type wth name: " << type_name);
```suggestion
            logError(DDSRECORDER_MCAP_HANDLER, "MCAP_WRITE | Failed to serialize DynamicType to idl for type with name: " << type_name);
```

2024-09-02 10:58 UTC, juanlofer-eprosima commented on ddsrecorder_participants/src/cpp/recorder/mcap/McapHandler.cpp
> +            logError(DDSRECORDER_MCAP_HANDLER, "MCAP_WRITE | Failed to serialize DynamicType to idl for type wth name: " << type_name);
Please substitute all log traces for EPROSIMA_LOG_X in all products.

2024-09-02 10:58 UTC, juanlofer-eprosima commented on ddsrecorder_participants/src/cpp/recorder/mcap/McapHandler.cpp
> +        // NOTE: Currently ROS2 types are not supported, change when supported
I would remove this note, what is currently not supported is ROS 2 endpoints sending dynamic types, but what this feature actually means is "store in ROS 2 format".

2024-09-02 10:58 UTC, juanlofer-eprosima commented on ddsrecorder_participants/src/cpp/recorder/mcap/McapHandler.cpp
> +            const auto ret = fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_object(
Please check this value is OK, and abort otherwise.

2024-09-02 10:58 UTC, juanlofer-eprosima commented on ddsrecorder_participants/src/cpp/recorder/mcap/McapHandler.cpp
> +        if (fastdds::dds::RETCODE_OK == fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_object(
And a log trace for the else case.

2024-09-02 10:58 UTC, juanlofer-eprosima commented on ddsrecorder_participants/src/cpp/recorder/mcap/McapHandler.cpp
> +        const fastdds::dds::xtypes::TypeIdentifier& type_identifier)
Assert that this type_identifier is EK_COMPLETE. I would add this assertion before calling this method in TypeObjectWriter.

2024-09-02 10:58 UTC, juanlofer-eprosima commented on ddsrecorder_participants/src/cpp/recorder/mcap/McapHandler.cpp
> +    type_identifiers.type_identifier1(type_identifier);
```suggestion
    NOTE: type_identifier is assumed to be complete
    type_identifiers.type_identifier1(type_identifier);
```

2024-09-03 09:31 UTC, LuciaEchevarria99 commented on ddsrecorder_participants/src/cpp/recorder/mcap/McapHandler.cpp
> +    fastdds::rtps::CDRMessage_t* cdr_message = new fastdds::rtps::CDRMessage_t(payload);
Already tested and working fine with repositories in branches/commits:
- foonathan_memory_vendor: master/ff121da
- fastcdr: master/e17fdc4
- fastdds: master/bfef427e2
- dev-utils: master/7e6c631
- ddspipe: integration/bump-3.0.0/c2189a7
- ddsrecordreplay: integration/bump-3.0.x/7e961e4

Some  errors apparently related with mcap appear:
`==457223== Use of uninitialised value of size 8
==457223==    at 0x4B0C943: mcap::internal::CRC32Table<3988292384ul, 8ul>::operator[](unsigned long) const (crc32.hpp:52)
==457223==    by 0x4AFD3AE: mcap::internal::crc32Update(unsigned int, std::byte const*, unsigned long) (crc32.hpp:91)
==457223==    by 0x4AE5993: mcap::McapWriter::write(mcap::Attachment&) (writer.inl:584)
==457223==    by 0x4B4E481: void eprosima::ddsrecorder::participants::McapWriter::write_nts_<mcap::Attachment>(mcap::Attachment const&) (McapWriter.cpp:229)
==457223==    by 0x4B4F463: eprosima::ddsrecorder::participants::McapWriter::write_attachment_nts_() (McapWriter.cpp:340)
==457223==    by 0x4B4E1F7: eprosima::ddsrecorder::participants::McapWriter::close_current_file_nts_() (McapWriter.cpp:210)
==457223==    by 0x4B4D249: eprosima::ddsrecorder::participants::McapWriter::disable() (McapWriter.cpp:96)
==457223==    by 0x4AE9C3B: eprosima::ddsrecorder::participants::McapHandler::stop(bool) (McapHandler.cpp:389)
==457223==    by 0x4AE7FE7: eprosima::ddsrecorder::participants::McapHandler::~McapHandler() (McapHandler.cpp:100)
==457223==    by 0x2393C7: void __gnu_cxx::new_allocator<eprosima::ddsrecorder::participants::McapHandler>::destroy<eprosima::ddsrecorder::participants::McapHandler>(eprosima::ddsrecorder::participants::McapHandler*) (new_allocator.h:168)
==457223==    by 0x239206: void std::allocator_traits<std::allocator<eprosima::ddsrecorder::participants::McapHandler> >::destroy<eprosima::ddsrecorder::participants::McapHandler>(std::allocator<eprosima::ddsrecorder::participants::McapHandler>&, eprosima::ddsrecorder::participants::McapHandler*) (alloc_traits.h:535)
==457223==    by 0x238A84: std::_Sp_counted_ptr_inplace<eprosima::ddsrecorder::participants::McapHandler, std::allocator<eprosima::ddsrecorder::participants::McapHandler>, (__gnu_cxx::_Lock_policy)2>::_M_dispose() (shared_ptr_base.h:528)
==457223==  Uninitialised value was created by a stack allocation
==457223==    at 0x4B4F380: eprosima::ddsrecorder::participants::McapWriter::write_attachment_nts_() (McapWriter.cpp:329)`

2024-09-04 06:32 UTC, LuciaEchevarria99 commented on resources/dds/TypeLookupService/TypeLookupServicePublisher.cpp
> +    // eprosima::fastrtps::types::DynamicDataHelper::print(dynamic_data_);
Example deleted

2024-09-04 06:32 UTC, LuciaEchevarria99 commented on resources/dds/TypeLookupService/TypeLookupServicePublisher.cpp
> +    // // internal_data sequence element 1
Example deleted

2024-09-16 09:11 UTC, juanlofer-eprosima commented on ddsrecorder/test/blackbox/mcap/McapFileCreationTest.cpp
> +// TEST(McapFileCreationTest, mcap_data_msgs)
Apply suggestion.

2024-09-16 09:17 UTC, juanlofer-eprosima commented on ddsrecorder/test/blackbox/mcap/McapFileCreationTest.cpp
> +    // eprosima::fastdds::dds::traits<eprosima::fastdds::dds::DynamicData>::ref_type dynamic_data_;
```suggestion
```

2024-09-16 09:17 UTC, juanlofer-eprosima commented on ddsrecorder/test/blackbox/mcap/McapFileCreationTest.cpp
> +        ros2_types ? create_publisher(test::ros2_topic_name, test::dds_type_name, test::DOMAIN) : create_publisher(
Undo change everywhere.

2024-09-16 09:35 UTC, juanlofer-eprosima commented on ddsreplayer/test/blackbox/mcap/McapFileReadTest.cpp
> +    ASSERT_GT(data.mean_ms_between_msgs, 98.5);
?

2024-09-16 09:35 UTC, juanlofer-eprosima commented on ddsreplayer/test/blackbox/mcap/McapFileReadWithTypeTest.cpp
> +    // ASSERT_EQ(data.message_msg, "Configuration");
?

2024-09-16 09:35 UTC, juanlofer-eprosima commented on docs/rst/recording/usage/usage.rst
Update documentation: especially the part concerning xtypes (remove fastdds configuration tutorial and final section in recorder configuration).

2024-09-16 09:35 UTC, juanlofer-eprosima commented on ddsrecorder/test/blackbox/mcap/McapLogErrorTests.cpp
> +TEST(McapEPROSIMA_LOG_ERRORTests, fail_to_open_file) {
Double check all substitutions are correct.

2024-09-16 09:35 UTC, juanlofer-eprosima commented on ddsreplayer/test/blackbox/mcap/McapFileReadTest.cpp
> +    ASSERT_EQ(data.min_index_msg, 4);
?

2024-09-16 09:35 UTC, juanlofer-eprosima commented on ddsrecorder/test/blackbox/mcap/McapFileCreationTest.cpp
> +        return;
Add log.

2024-09-16 09:35 UTC, juanlofer-eprosima commented on ddsrecorder/test/blackbox/mcap/McapFileCreationTest.cpp
> +        return nullptr;
Add log.

2024-09-16 09:35 UTC, juanlofer-eprosima commented on resources/dds/TypeLookupService/TypeLookupServicePublisher.cpp
> +    // eprosima::fastrtps::types::DynamicDataHelper::print(dynamic_data_);
Update documentation accordingly.

2024-09-16 09:58 UTC, juanlofer-eprosima commented on ddsreplayer/src/cpp/tool/DdsReplayer.cpp
>  {
Delete unused constructor (with outdated docstring).

2024-09-16 09:58 UTC, juanlofer-eprosima commented on ddsreplayer/src/cpp/tool/DdsReplayer.cpp
> +fastdds::dds::xtypes::TypeIdentifier DdsReplayer::deserialize_type_identifier_(
Reuse implementation code with one templated method as in recorder?

2024-09-16 09:58 UTC, juanlofer-eprosima commented on ddsrecorder_participants/include/ddsrecorder_participants/replayer/ReplayerParticipant.hpp
> +    bool replay_types = true;
Cannot this be protected?

2024-09-16 09:58 UTC, juanlofer-eprosima commented on ddsrecorder_participants/src/cpp/replayer/ReplayerParticipant.cpp
> +
```suggestion
```

2024-09-16 09:58 UTC, juanlofer-eprosima commented on ddsreplayer/src/cpp/tool/DdsReplayer.cpp
> +        // }
Delete.

2024-09-16 10:02 UTC, juanlofer-eprosima requested changes
Please update gtest version to 1.12 , and remove note about publish-types in monitoring configuration sections.

2024-09-16 12:23 UTC, juanlofer-eprosima requested changes

2024-09-16 12:23 UTC, juanlofer-eprosima commented on ddsrecorder/test/blackbox/mcap/McapFileCreationTest.cpp
> +#include <cpp_utils/testing/gtest_aux.hpp>
This should be just before ``#include <gtest/gtest.h>

2024-09-16 12:47 UTC, juanlofer-eprosima requested changes

2024-09-16 12:47 UTC, juanlofer-eprosima commented on ddsrecorder_participants/include/ddsrecorder_participants/recorder/mcap/McapHandler.hpp
> +            const fastdds::dds::DynamicType::_ref_type& dynamic_type,
Update docstring.

2024-09-16 12:47 UTC, juanlofer-eprosima commented on ddsrecorder_participants/include/ddsrecorder_participants/recorder/mcap/McapHandler.hpp
> +    bool store_dynamic_type_(
Update docstring.

2024-09-16 12:47 UTC, juanlofer-eprosima commented on ddsrecorder_participants/include/ddsrecorder_participants/recorder/mcap/McapHandler.hpp
> +    bool store_dynamic_type_(
Update docstring.

2024-09-16 12:47 UTC, juanlofer-eprosima commented on ddsrecorder_participants/include/ddsrecorder_participants/recorder/mcap/McapHandler.hpp
> +     * @brief TODO.
Please do.

2024-09-16 12:56 UTC, juanlofer-eprosima requested changes

2024-09-16 12:56 UTC, juanlofer-eprosima commented on ddsrecorder_participants/src/cpp/recorder/mcap/McapHandler.cpp
> +    catch(const utils::InconsistencyException& e)
```suggestion
    catch (const utils::InconsistencyException& e)
```

2024-09-17 08:13 UTC, LuciaEchevarria99 commented on ddsrecorder/test/blackbox/mcap/McapFileCreationTest.cpp
> +        ros2_types ? create_publisher(test::ros2_topic_name, test::dds_type_name, test::DOMAIN) : create_publisher(
I added a note explaining the situation

2024-09-17 08:18 UTC, juanlofer-eprosima approved these changes
LGTM

2024-09-17 08:19 UTC, merged