[21413] Record data in SQL
eProsima/DDS-Record-Replay pull request #173
Opened 2024-12-19 09:46 UTC by EugenioCollado

Code improvements:

-     Make a Serializer to serialize and deserialize TopicQoS, TypeObjects, TypeIdentifiers, and DynamicTypes.
-     Make a time_utils to convert between different time formats.
-     Make the DdsRecorder and the DdsReplayer agnostic of the output format.
-     Refactor McapLogErrorTest to improve its readability.

Configuration improvements:

-     Move cleanup-period and max-pending-samples from specs to recorder.
-     Configure safety-margin as a string (100MB, 128GiB, etc).

Bug fixes:

-     Avoid creating a payload when replaying a message in a topic without a reader.
-     Fix assert in ROS 2 topics.

Potential TODOs:

-     Separate data storage calls to dedicated thread

2025-02-07 11:36 UTC, juanlofer-eprosima requested changes

2025-02-07 11:36 UTC, juanlofer-eprosima commented on ddsrecorder_participants/src/cpp/recorder/output/BaseHandler.cpp
> +    samples_buffer_.remove_if([&](const auto sample)
Why pass by value now? Avoid copy.

2025-02-07 11:36 UTC, juanlofer-eprosima commented on ddsrecorder_participants/src/cpp/recorder/mcap/McapHandler.cpp
>      }
Could you please encapsulate this in a parent method?

2025-02-07 11:38 UTC, juanlofer-eprosima commented on ddsrecorder_participants/src/cpp/recorder/output/BaseHandler.cpp
> +    logInfo(DDSRECORDER_DATA_HANDLER, "Destroying handler.");
Please change elsewhere.

2025-07-04 09:52 UTC, Mario-DL commented on ddsrecorder/CMakeLists.txt
> +set(CMAKE_SYSTEM_VERSION 10.0)
I removed it, but lets see if that does not give problems in windows. Anyways, I think it should no be needed

2025-07-04 09:53 UTC, Mario-DL commented on ddsrecorder/CMakeLists.txt
> +enable_language(C)
I also removed it from here. Lets see if I found further problems with that in other platforms different from Ubuntu

2025-07-04 09:57 UTC, Mario-DL commented on ddsrecorder/src/cpp/main.cpp
> +                }
Leaving as it is for the moment

2025-07-04 10:01 UTC, Mario-DL commented on ddsrecorder/src/cpp/tool/DdsRecorder.hpp
> +    void sql_on_disk_full();
In the refactor I included before the review I left just one callback passed to the handlers (if defined)

2025-07-04 10:02 UTC, Mario-DL commented on ddsrecorder/src/cpp/tool/DdsRecorder.hpp
> +    std::shared_ptr<ddspipe::participants::SchemaParticipant> sql_recorder_participant_;
Does not apply as a consequence of the refactor

2025-07-04 10:04 UTC, Mario-DL commented on ddsrecorder/src/cpp/tool/DdsRecorder.cpp
> +
I traced down some extra spaces in general and I think I tackled this one

2025-07-04 10:06 UTC, Mario-DL commented on ddsrecorder/src/cpp/tool/DdsRecorder.cpp
> +    }
Thats similar to what I did on the refactor. I grouped all the handlers (contexts) in a collection. See the comment below

2025-07-04 10:08 UTC, Mario-DL commented on ddsrecorder/src/cpp/tool/DdsRecorder.cpp
> +        configuration_.mcap_enabled = false;
I just left the `simulated_control_event()` part. The checking if `event_handler_` is `nullptr` although it could race I consider it fair enough to be left as it is

2025-07-04 10:08 UTC, Mario-DL commented on ddsrecorder/src/cpp/tool/DdsRecorder.cpp
> +void DdsRecorder::sql_on_disk_full()
Same comment as above

2025-07-04 10:27 UTC, Mario-DL commented on ddsrecorder/test/blackbox/FileCreationTest.hpp
> +        std::this_thread::sleep_for(std::chrono::milliseconds(100));
I aggree. I substituted it with a `wait_for_matching()` (on the writer side, since it already is TRANSIENT_LOCAL)

2025-07-04 10:30 UTC, Mario-DL commented on ddsrecorder/test/blackbox/FileCreationTest.hpp
> +        topic_ = participant_->create_topic(topic_name, "HelloWorld", fastdds::dds::TOPIC_QOS_DEFAULT);
I think so, but introduced a new `recreate_datawriter_()` for those tests needing a ros2 manged name for the type attached to the topic

2025-07-04 10:53 UTC, Mario-DL commented on ddsrecorder/test/blackbox/FileCreationTest.hpp
> +        create_datawriter_();
Related to the previous answer

2025-07-04 10:54 UTC, Mario-DL commented on ddsrecorder_participants/include/ddsrecorder_participants/common/serialize/Serializer.hpp
> +class DDSRECORDER_PARTICIPANTS_DllAPI Serializer
Yes, that makes all the methods and members of class to be exported instead of marking them individually. Seems fair enough to me

2025-07-07 07:32 UTC, Mario-DL commented on ddsrecorder_participants/include/ddsrecorder_participants/common/serialize/Serializer.hpp
> +// Explicitly declare the specializations
Since in `deserialize` the return type is the one that changes, I think we need to explicitly do that in this case (only for deserialization). Anyways, I changed the `(de)serialize` methods to received an `[out] ` argument instead so this is no longer needed

2025-07-07 08:35 UTC, Mario-DL commented on ddsrecorder_participants/include/ddsrecorder_participants/common/types/dynamic_types_collection/DynamicTypesCollectionCdrAux.hpp
I took the chance also to regenerate the types with `Gen 4.1.0`.
I think we would need to rethink the way types are included in the project (separated in `include/` and `/src`) its a headache (and not practical) to be always changing the include paths after regenerating and splitting

2025-07-07 08:51 UTC, Mario-DL commented on ddsrecorder_participants/src/cpp/recorder/output/BaseHandler.cpp
> +    logInfo(DDSRECORDER_DATA_HANDLER, "Destroying handler.");
It is being called in the derived classes

2025-07-07 09:05 UTC, Mario-DL commented on resources/dds/TypeLookupService/TypeLookupServicePublisher.h
> +// Copyright 2023 Proyectos y Sistemas de Mantenimiento SL (eProsima).
I am removing these files

2025-07-07 09:06 UTC, Mario-DL commented on resources/dds/TypeLookupService/TypeLookupServicePublisher.cpp
> +    // // internal_data sequence element 1
Related to the above comment

2025-07-07 09:06 UTC, Mario-DL commented on resources/dds/TypeLookupService/TypeLookupServicePublisher.h
> +    static void stop();
Related to the above comment

2025-07-07 09:07 UTC, Mario-DL commented on docs/rst/recording/usage/configuration.rst
> -      max-pending-samples: 10
Pending to decide

2025-07-07 09:08 UTC, Mario-DL commented on resources/dds/TypeLookupService/TypeLookupServiceSubscriber.cpp
Yes

2025-07-07 09:09 UTC, Mario-DL commented on docs/rst/recording/usage/configuration.rst
> +The ``data-format`` tag allows users to specify the format in which data is stored in the SQL database.
Leaving that for further PR

2025-07-07 09:25 UTC, Mario-DL commented on resources/configurations/recorder/complete_config.yaml
I kept it for the moment

2025-07-07 09:56 UTC, Mario-DL commented on ddsreplayer/src/cpp/tool/DdsReplayer.cpp
> +    if (input_file.size() >= 3 && input_file.substr(input_file.size() - 3) == ".db")
I included a little regex to get the filename extension. Included cli arguments its another feature to me and can be tackled in the future.

2025-07-07 10:04 UTC, Mario-DL commented on ddsreplayer/src/cpp/tool/DdsReplayer.cpp
> -using namespace eprosima::utils;
I think that the code is still legible even without them, so I am leaving them removed

2025-07-07 10:16 UTC, Mario-DL commented on ddsrecorder_participants/src/cpp/recorder/mcap/McapHandler.cpp
>      }
Whats more , I think we can directly call the parent method since the checks are performed there

2025-07-07 10:24 UTC, Mario-DL commented on ddsrecorder_participants/src/cpp/recorder/mcap/McapHandler.cpp
> +    process_new_sample_nts_(std::make_shared<const McapMessage>(
I will check it ahead

2025-07-07 10:53 UTC, Mario-DL commented on .github/workflows/reusable-ubuntu-ci.yml
> +          ASAN_OPTIONS: detect_odr_violation=0
I am keeping this for the moment but will check if it is still needed

2025-07-15 06:15 UTC, Mario-DL commented on ddsrecorder/CMakeLists.txt
> +enable_language(C)
Finally, this including this directive is needed for the `.c` sqlite sources to correctly link

2025-07-15 06:15 UTC, Mario-DL commented on ddsrecorder/CMakeLists.txt
> +set(CMAKE_SYSTEM_VERSION 10.0)
Removing this was finally okay

2025-07-24 05:45 UTC, emiliocuestaf submitted a review, later dismissed
In general, LGTM

2025-07-24 05:45 UTC, emiliocuestaf commented on docs/rst/recording/usage/configuration.rst
> +### Safety Margin
These titles in the format "### X" are not rendering properly. Maybe its due to the change of theme in the docs. Please consider using the 

Sample title
"""""""""""""""
and

Sample section
^^^^^^^^^^^^^^^^^^

formats

2025-07-24 05:45 UTC, emiliocuestaf commented on .github/workflows/reusable-ubuntu-ci.yml
> +          ASAN_OPTIONS: detect_odr_violation=0
Did you finally check this?

2025-07-24 05:45 UTC, emiliocuestaf commented on ddsrecorder_participants/include/ddsrecorder_participants/recorder/handler/sql/impl/SqlWriter.ipp
> +        try{
I think this line causes uncrustify to fail, eitherway its better to run it in the whole file

2025-07-24 05:45 UTC, emiliocuestaf commented on ddsrecorder_participants/include/ddsrecorder_participants/recorder/handler/mcap/McapHandlerConfiguration.hpp
> +    McapHandlerConfiguration(
NIT: Missing doxygen for the constructor

2025-07-24 05:45 UTC, emiliocuestaf commented on ddsrecorder_participants/include/ddsrecorder_participants/recorder/handler/mcap/McapSizeTracker.hpp
>      std::uint64_t potential_mcap_size_{MCAP_FILE_OVERHEAD}; // TODO: move initialization to init, and also set disk_full_ to false
Unrelated to this PR, but what about this TODO? It shouldn't be hard to move

2025-07-24 05:45 UTC, emiliocuestaf commented on ddsrecorder_participants/include/ddsrecorder_participants/recorder/handler/mcap/McapSizeTracker.hpp
> +    std::uint64_t checked_written_mcap_size_{0};
NIT: Same thing with these inits

2025-07-24 05:45 UTC, emiliocuestaf commented on ddsrecorder_participants/include/ddsrecorder_participants/recorder/handler/mcap/McapWriter.hpp
> +class DDSRECORDER_PARTICIPANTS_DllAPI McapWriter : public BaseWriter
NIT: Missing doxygen in the class and in the constructor below

2025-07-24 05:45 UTC, emiliocuestaf commented on ddsrecorder_participants/include/ddsrecorder_participants/recorder/handler/mcap/McapWriter.hpp
> +     * - @throws \c InitializationException if the output library fails to open a new file.
NIT: I guess this "MCAP" was aready ok since the file is McapWriter.hpp

2025-07-24 05:45 UTC, emiliocuestaf commented on ddsrecorder_participants/include/ddsrecorder_participants/recorder/handler/sql/SqlHandler.hpp
> +     * Opens temporal MCAP file where data is to be written.
Multiple mentions to MCAP in this file

2025-07-24 05:45 UTC, emiliocuestaf commented on ddsrecorder_participants/include/ddsrecorder_participants/recorder/handler/sql/SqlHandler.hpp
> +     * Closes temporal MCAP file, and renames it with filename given in configuration.
Here

2025-07-24 05:45 UTC, emiliocuestaf commented on ddsrecorder_participants/include/ddsrecorder_participants/recorder/handler/sql/SqlHandler.hpp
> +     * @throw InitializationException if creation fails (fail to open MCAP file).
Here

2025-07-24 05:45 UTC, emiliocuestaf commented on ddsrecorder_participants/include/ddsrecorder_participants/recorder/handler/sql/SqlHandlerConfiguration.hpp
> +    SqlHandlerConfiguration(
NIT: Missing doxygen here

2025-07-24 05:45 UTC, emiliocuestaf commented on ddsrecorder_participants/include/ddsrecorder_participants/recorder/handler/BaseHandlerConfiguration.hpp
> +    BaseHandlerConfiguration(
Missing doxygen here, at least the base class should have it detailed. McapHandlerConfiguration and SqlHandlerConfiguration are missing this too

2025-07-24 05:45 UTC, emiliocuestaf commented on ddsrecorder_participants/include/ddsrecorder_participants/recorder/handler/sql/impl/SqlWriter.ipp
> + * @file SqlWriter.cpp
File should be SqlWriter.ipp

2025-07-24 05:45 UTC, emiliocuestaf commented on ddsrecorder_participants/include/ddsrecorder_participants/recorder/handler/mcap/impl/McapWriter.ipp
IDK why I cant comment in the @file tag, but I think it should be .ipp not .cpp

2025-07-24 05:45 UTC, emiliocuestaf commented on ddsrecorder_participants/include/ddsrecorder_participants/recorder/message/BaseMessage.hpp
> +     * @brief TODO
I think we should do the TODO's, I can take them after the review

2025-07-24 05:45 UTC, emiliocuestaf commented on ddsrecorder_participants/include/ddsrecorder_participants/recorder/message/McapMessage.hpp
> +            const mcap::ChannelId channel_id,
At least those parameter thar are not in the base case (topic and channel_id) should be commented

2025-07-24 05:45 UTC, emiliocuestaf commented on ddsrecorder_participants/include/ddsrecorder_participants/recorder/message/SqlMessage.hpp
> +    SqlMessage(
NIT: Detail parameters. I don't know if it's usual to not comment all the parameters. **Please feel free to ignore my pedantry if this does not proceed**

2025-07-24 05:45 UTC, emiliocuestaf commented on ddsrecorder_participants/include/ddsrecorder_participants/recorder/output/OutputSettings.hpp
> +    bool set_resource_limits(
I understand the need of this function but it is a bit misleading to call it "set_...". Maybe "cap_resource_limits"? or "adequate_resource_limits"?

2025-07-24 05:45 UTC, emiliocuestaf commented on ddsrecorder_participants/include/ddsrecorder_participants/recorder/output/ResourceLimits.hpp
> + * @file OutputSettings.hpp
file name is wrong, its ResourceLimits.hpp

2025-07-24 05:45 UTC, emiliocuestaf commented on ddsrecorder_participants/include/ddsrecorder_participants/recorder/output/OutputSettings.hpp
> +    bool set_resource_limits(
I'd also consider moving it to ResourceLimits.hpp

2025-07-24 05:45 UTC, emiliocuestaf commented on ddsrecorder_participants/include/ddsrecorder_participants/replayer/McapReaderParticipant.hpp
>      DDSRECORDER_PARTICIPANTS_DllAPI
Wouldn't it be better to add DDSRECORDER_PARTICIPANTS_DllAPI to the whole class? I guess this could be another PR

2025-07-24 05:45 UTC, emiliocuestaf commented on ddsrecorder_participants/include/ddsrecorder_participants/replayer/McapReaderParticipant.hpp
>      McapReaderParticipant(
Doxygen comment missing

2025-07-24 05:45 UTC, emiliocuestaf commented on ddsrecorder_participants/project_settings.cmake
> +    sqlite # Not header-only though, need to link .c
Just out of curiosity, why do we need to link  .c?

2025-07-24 05:45 UTC, emiliocuestaf commented on ddsrecorder_participants/src/cpp/recorder/handler/mcap/McapSizeTracker.cpp
>      // TODO: add check that space is greater than file overhead
Just a reminder of this TODO

2025-07-24 05:45 UTC, emiliocuestaf commented on ddsrecorder_participants/src/cpp/recorder/message/SqlMessage.cpp
> +void SqlMessage::deserialize(
I also think it makes more sense for the handler to know how to serialize/deserialize for a concrete target and the "message" classes to contain only the data. I don't have a strong opinion on this though.

2025-07-24 09:07 UTC, emiliocuestaf reviewed
LGTM

2025-07-24 09:07 UTC, emiliocuestaf commented on ddsreplayer/src/cpp/main.cpp
There are 2 or 3 mentions to MCAP here that should be changed to "input file" or similar

2025-07-28 08:01 UTC, Mario-DL commented on .github/workflows/reusable-ubuntu-ci.yml
> +          ASAN_OPTIONS: detect_odr_violation=0
I forgot, now I am removing it and lets see the ci

2025-07-28 08:13 UTC, Mario-DL commented on ddsrecorder_participants/include/ddsrecorder_participants/recorder/handler/mcap/McapSizeTracker.hpp
>      std::uint64_t potential_mcap_size_{MCAP_FILE_OVERHEAD}; // TODO: move initialization to init, and also set disk_full_ to false
Since this is unrelated to the PR it should be addressed in a follow up

2025-07-28 08:14 UTC, Mario-DL commented on ddsrecorder_participants/include/ddsrecorder_participants/recorder/handler/mcap/McapSizeTracker.hpp
> +    std::uint64_t checked_written_mcap_size_{0};
Same here

2025-07-28 08:35 UTC, Mario-DL commented on ddsrecorder_participants/include/ddsrecorder_participants/recorder/message/BaseMessage.hpp
> +     * @brief TODO
I can doxygen these

2025-07-28 08:52 UTC, Mario-DL commented on ddsrecorder_participants/include/ddsrecorder_participants/recorder/output/OutputSettings.hpp
> +    bool set_resource_limits(
I find it ok both the name and the place since it is filling the `resource_limits` member within `OutputSettings`

2025-07-28 08:55 UTC, Mario-DL commented on ddsrecorder_participants/include/ddsrecorder_participants/replayer/McapReaderParticipant.hpp
>      DDSRECORDER_PARTICIPANTS_DllAPI
The thing is by doing that you force not only the methods but the members to be exported too, so for this PR is not needed

2025-07-28 08:57 UTC, Mario-DL commented on ddsrecorder_participants/src/cpp/recorder/handler/mcap/McapSizeTracker.cpp
>      // TODO: add check that space is greater than file overhead
Can be addressed in a follow up

2025-07-28 09:07 UTC, Mario-DL commented on ddsrecorder_participants/project_settings.cmake
> +    sqlite # Not header-only though, need to link .c
The `MODULE_THIRDPARTY_HEADERONLY` just includes the directory of the `thirdparty` paths (in this case, the `thirdparty/sqlite`) in the CMake's `include_directories` when building. I updated the comment since it is not "linking" but just including those directories in the sources for the libary compilation.

2025-07-28 09:50 UTC, Mario-DL commented on ddsrecorder_participants/src/cpp/recorder/message/SqlMessage.cpp
> +void SqlMessage::deserialize(
For me, keeping it in the `SqlMessage` is okey for now. The message is who actually ecapsulates the payload and stores the output in its `data_json` member. In any case, I think that the refactor should lie in a different PR

2025-07-28 10:14 UTC, Mario-DL commented on .github/workflows/reusable-ubuntu-ci.yml
> +          ASAN_OPTIONS: detect_odr_violation=0
It is required to avoid odr_violations warnings in `sqlite.c` files

2025-07-28 12:22 UTC, emiliocuestaf commented on ddsrecorder_participants/include/ddsrecorder_participants/common/serialize/impl/Serializer.ipp
this file is not uncrustify compliant

2025-07-28 12:26 UTC, emiliocuestaf commented
LGTM CI pending

2025-07-28 14:22 UTC, juanlofer-eprosima approved these changes

2025-07-28 14:23 UTC, merged