Recorder participant [16665]
eProsima/DDS-Record-Replay pull request #2
Opened 2022-12-26 13:00 UTC by jparisu

After #1

2023-01-11 10:17 UTC, juanlofer-eprosima requested changes

2023-01-11 10:17 UTC, juanlofer-eprosima commented on ddsrecorder/src/cpp/core/ParticipantFactory.cpp
> +            // DummyParticipant
```suggestion
            // Recorder Participant
```

2023-01-11 10:17 UTC, juanlofer-eprosima commented on ddsrecorder/src/cpp/participant/implementations/recorder/RecorderParticipant.hpp
> +     * @brief Construct a new Dummy Participant object
```suggestion
     * @brief Construct a new Recorder Participant object
```

2023-01-11 10:17 UTC, juanlofer-eprosima commented on ddsrecorder/src/cpp/participant/implementations/recorder/RecorderParticipant.hpp
> +     * @brief Destroy the Dummy Participant object
```suggestion
     * @brief Destroy the Recorder Participant object
```

2023-01-11 10:17 UTC, juanlofer-eprosima commented on ddsrecorder/src/cpp/reader/implementations/auxiliar/InternalReader.hpp
> +    using DataReceviedType = utils::Atomicable<std::queue<std::unique_ptr<types::DataReceived>>>;
```suggestion
    using DataReceivedType = utils::Atomicable<std::queue<std::unique_ptr<types::DataReceived>>>;
```

2023-01-11 10:17 UTC, juanlofer-eprosima commented on ddsrecorder/src/cpp/participant/implementations/recorder/RecorderParticipant.cpp
> +            if (endpoint_discovered.discoverer_participant_id() != this->id())
```suggestion
            if (endpoint_discovered.is_writer() && endpoint_discovered.discoverer_participant_id() != this->id())
```

2023-01-12 08:58 UTC, rsanchez15 requested changes
Change ddsrecorder.repos to pull master/main branches

2023-01-12 09:28 UTC, juanlofer-eprosima approved these changes
LGTM

2023-01-12 09:28 UTC, rsanchez15 approved these changes

2023-01-12 09:29 UTC, merged

2026-07-17 08:51 UTC, Danipiza commented
I added "#2" in the flaky fix PR trying to mention the second flaky tests, but it mentioned this PR